In [2]:
import image_metadata
import streetscore

ModuleNotFoundError: No module named 'piexif'

In [4]:
from huggingface_hub import login
login(token=token)

ModuleNotFoundError: No module named 'huggingface_hub'

In [9]:
gdf = image_metadata.images_gdf(
    "/home/miguel/Documents/UNI/Master/2/ProjektVerkehr/images/Anlagenring/FriedbergerTor"
)
gdf.head(5)

,path,filename,datetime,heading,x,y,geometry
0,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202513.jpg,2026-05-28 09:44:30.302758932,76.54,8.689764,50.118931,POINT (8.68976 50.11893)
1,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202138.jpg,2026-05-28 09:44:29.210757494,29.50,8.688531,50.118536,POINT (8.68853 50.11854)
2,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202751.jpg,2026-05-28 09:44:30.750759363,118.55,8.691603,50.119200,POINT (8.6916 50.1192)
3,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202000.jpg,2026-05-28 09:44:28.677757025,149.68,8.687361,50.119244,POINT (8.68736 50.11924)
4,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526203045.jpg,2026-05-28 09:44:31.169759750,41.48,8.692847,50.118997,POINT (8.69285 50.119)

In [10]:
gdf = streetscore.run(gdf)

Using device: cuda:0

Fetching 7 files: 100%|██████████| 7/7 [00:00<00:00, 13400.33it/s]

######### safety #########

100%|██████████| 32/32 [00:03<00:00, 10.56it/s]

safety prediction complete.

######### lively #########

100%|██████████| 32/32 [00:02<00:00, 11.52it/s]

lively prediction complete.

######### wealthy #########

100%|██████████| 32/32 [00:02<00:00, 11.60it/s]

wealthy prediction complete.

######### beautiful #########

100%|██████████| 32/32 [00:02<00:00, 11.24it/s]

beautiful prediction complete.

######### boring #########

100%|██████████| 32/32 [00:02<00:00, 11.67it/s]

boring prediction complete.

######### depressing #########

100%|██████████| 32/32 [00:02<00:00, 11.75it/s]

depressing prediction complete.

In [13]:
gdf.head(5)

,path,filename,datetime,heading,x,y,geometry,safety,lively,wealthy,beautiful,boring,depressing
0,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202513.jpg,2026-05-28 09:44:30.302758932,76.54,8.689764,50.118931,POINT (8.68976 50.11893),4.67,4.08,7.20,8.63,6.49,5.23
1,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202138.jpg,2026-05-28 09:44:29.210757494,29.50,8.688531,50.118536,POINT (8.68853 50.11854),7.32,8.30,6.75,9.02,3.17,1.32
2,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202751.jpg,2026-05-28 09:44:30.750759363,118.55,8.691603,50.119200,POINT (8.6916 50.1192),6.84,4.12,7.84,7.89,7.95,5.08
3,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202000.jpg,2026-05-28 09:44:28.677757025,149.68,8.687361,50.119244,POINT (8.68736 50.11924),1.89,3.57,4.67,5.07,2.67,5.08
4,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526203045.jpg,2026-05-28 09:44:31.169759750,41.48,8.692847,50.118997,POINT (8.69285 50.119),6.57,9.54,8.26,9.43,6.67,1.77

In [12]:
gdf.to_file("/home/miguel/Documents/UNI/Master/2/ProjektVerkehr/images/Anlagenring/FriedbergerTor/streetscore_results.gpkg")

In [15]:
positive_tags = [
    "safety",
    "lively",
    "wealthy",
    "beautiful",
]
negative_tags = [
    "boring",
    "depressing",
]

n_pos = len(positive_tags)
n_neg = len(negative_tags)

pos_mean = gdf[positive_tags].mean(axis=1)
neg_mean = gdf[negative_tags].mean(axis=1)

gdf["score"] = (
    (pos_mean * n_pos) - (neg_mean * n_neg) + 10 * n_neg
) / (n_pos + n_neg)
gdf.head(5)

,path,filename,datetime,heading,x,y,geometry,safety,lively,wealthy,beautiful,boring,depressing,score
0,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202513.jpg,2026-05-28 09:44:30.302758932,76.54,8.689764,50.118931,POINT (8.68976 50.11893),4.67,4.08,7.20,8.63,6.49,5.23,5.476667
1,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202138.jpg,2026-05-28 09:44:29.210757494,29.50,8.688531,50.118536,POINT (8.68853 50.11854),7.32,8.30,6.75,9.02,3.17,1.32,7.816667
2,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202751.jpg,2026-05-28 09:44:30.750759363,118.55,8.691603,50.119200,POINT (8.6916 50.1192),6.84,4.12,7.84,7.89,7.95,5.08,5.610000
3,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526202000.jpg,2026-05-28 09:44:28.677757025,149.68,8.687361,50.119244,POINT (8.68736 50.11924),1.89,3.57,4.67,5.07,2.67,5.08,4.575000
4,/home/miguel/Documents/UNI/Master/2/ProjektVer...,IMG20260526203045.jpg,2026-05-28 09:44:31.169759750,41.48,8.692847,50.118997,POINT (8.69285 50.119),6.57,9.54,8.26,9.43,6.67,1.77,7.560000

In [61]:
import folium
import pandas as pd
import branca.colormap as cm
from pyproj import Geod

# =========================
# GEODESIC ENGINE
# =========================
geod = Geod(ellps="WGS84")

def create_map(gdf, positive_tags, negative_tags):
    df = gdf.copy()
    
    # Initialize map
    m = folium.Map(location=[df.y.mean(), df.x.mean()], zoom_start=18, tiles=None)

    # Google Hybrid with 0.5 opacity
    folium.TileLayer(
        tiles="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
        attr="Google",
        name="Google Hybrid",
        overlay=True,
        opacity=0.5
    ).add_to(m)

    # Colormaps
    pos_cmap = cm.LinearColormap(["red", "yellow", "green"], vmin=0, vmax=10)
    neg_cmap = cm.LinearColormap(["green", "yellow", "red"], vmin=0, vmax=10)

    # Create FeatureGroups
    groups = {t: folium.FeatureGroup(name=t, show=(t == 'score')).add_to(m) 
              for t in ['score'] + positive_tags + negative_tags}

    # Drawing function
    def add_to_layer(group, lat, lon, heading, val, cmap, tt):
        color = cmap(val)
        
        # Opaque Marker
        folium.CircleMarker(
            (lat, lon), radius=8, color=color, 
            fill=True, fill_color=color, fill_opacity=1.0, 
            opacity=1.0, weight=2, tooltip=tt
        ).add_to(group)
        
        # Arrow
        if pd.notna(heading):
            lon2, lat2, _ = geod.fwd(lon, lat, heading, 8) 
            folium.PolyLine(
                [(lat, lon), (lat2, lon2)], 
                color=color, weight=5, opacity=1.0
            ).add_to(group)

    # Main Loop
    for _, row in df.iterrows():
        lat, lon = row.y, row.x
        h = row.heading
        
        # Tooltip with every value on a new line
        tt = f"<b>Score: {row.get('score', 0):.2f}</b><br>"
        tt += "<u><b>Positive:</b></u><br>"
        for t in positive_tags:
            tt += f"{t}: {row.get(t, 0):.2f}<br>"
        tt += "<u><b>Negative:</b></u><br>"
        for t in negative_tags:
            tt += f"{t}: {row.get(t, 0):.2f}<br>"
        
        # Draw Score
        add_to_layer(groups['score'], lat, lon, h, row.get('score', 0), pos_cmap, tt)
        
        # Draw Tags
        for t in positive_tags:
            if pd.notna(row.get(t)):
                add_to_layer(groups[t], lat, lon, h, row[t], pos_cmap, tt)
        for t in negative_tags:
            if pd.notna(row.get(t)):
                add_to_layer(groups[t], lat, lon, h, row[t], neg_cmap, tt)

    folium.LayerControl(collapsed=False).add_to(m)
    return m

In [67]:
import folium
import pandas as pd
import branca.colormap as cm
from pyproj import Geod

geod = Geod(ellps="WGS84")

def create_map(gdf, positive_tags, negative_tags):
    df = gdf.copy()
    m = folium.Map(location=[df.y.mean(), df.x.mean()], zoom_start=18, tiles=None)

    folium.TileLayer(
        tiles="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
        attr="Google",
        name="Google Hybrid",
        overlay=True,
        opacity=0.5
    ).add_to(m)

    pos_cmap = cm.LinearColormap(["red", "yellow", "green"], vmin=0, vmax=10)
    neg_cmap = cm.LinearColormap(["green", "yellow", "red"], vmin=0, vmax=10)

    groups = {t: folium.FeatureGroup(name=t, show=(t == 'score')).add_to(m) 
              for t in ['score'] + positive_tags + negative_tags}

    def add_to_layer(group, row, lat, lon, heading, val, cmap, tt, html_popup):
        color = cmap(val)
        
        # Opaque Marker with black border (weight=1, color='black')
        folium.CircleMarker(
            (lat, lon), radius=8, color='black', 
            fill=True, fill_color=color, fill_opacity=1.0, 
            opacity=1.0, weight=1, tooltip=tt,
            popup=folium.Popup(html_popup, max_width=500)
        ).add_to(group)
        
        # Arrow (Draw thick black line first, then thinner colored line on top)
        if pd.notna(heading):
            lon2, lat2, _ = geod.fwd(lon, lat, heading, 8) 
            # Black border line
            folium.PolyLine([(lat, lon), (lat2, lon2)], color='black', weight=7, opacity=1.0).add_to(group)
            # Colored main line
            folium.PolyLine([(lat, lon), (lat2, lon2)], color=color, weight=5, opacity=1.0).add_to(group)

    for _, row in df.iterrows():
        lat, lon = row.y, row.x
        h = row.heading
        
        # Build text
        tt = f"<b>Score: {row.get('score', 0):.2f}</b><br><u><b>Pos:</b></u><br>"
        tt += "<br>".join([f"{t}: {row.get(t,0):.2f}" for t in positive_tags])
        tt += "<br><u><b>Neg:</b></u><br>"
        tt += "<br>".join([f"{t}: {row.get(t,0):.2f}" for t in negative_tags])
        
        img_path = row.get('path', '')
        html_popup = f"""
        <div style="display: flex; flex-direction: row; align-items: flex-start; width: 400px;">
            <div style="flex: 1; margin-right: 10px; font-size: 12px;">{tt}</div>
            <div style="flex: 1;">
                <a href="{img_path}" target="_blank">
                    <img src="{img_path}" style="width:150px; border:1px solid #ccc; cursor:pointer;">
                </a>
            </div>
        </div>
        """
        
        add_to_layer(groups['score'], row, lat, lon, h, row.get('score', 0), pos_cmap, tt, html_popup)
        for t in positive_tags:
            if pd.notna(row.get(t)):
                add_to_layer(groups[t], row, lat, lon, h, row[t], pos_cmap, tt, html_popup)
        for t in negative_tags:
            if pd.notna(row.get(t)):
                add_to_layer(groups[t], row, lat, lon, h, row[t], neg_cmap, tt, html_popup)

    folium.LayerControl(collapsed=False).add_to(m)
    return m

In [73]:
import folium
import pandas as pd
import branca.colormap as cm
from pyproj import Geod

# =========================
# GEODESIC ENGINE
# =========================
geod = Geod(ellps="WGS84")

def create_map(gdf, positive_tags, negative_tags):
    df = gdf.copy()
    
    # Initialize map
    m = folium.Map(location=[df.y.mean(), df.x.mean()], zoom_start=18, tiles=None)

    # Google Hybrid with 0.5 opacity
    folium.TileLayer(
        tiles="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
        attr="Google",
        name="Google Hybrid",
        overlay=True,
        opacity=0.5
    ).add_to(m)

    # Colormaps
    pos_cmap = cm.LinearColormap(["red", "yellow", "green"], vmin=0, vmax=10)
    neg_cmap = cm.LinearColormap(["green", "yellow", "red"], vmin=0, vmax=10)

    # Create FeatureGroups
    groups = {t: folium.FeatureGroup(name=t, show=(t == 'score')).add_to(m) 
              for t in ['score'] + positive_tags + negative_tags}

    # Helper to draw arrow with black border
    def draw_arrow(group, lat, lon, heading, color, tt, html_popup):
        lon2, lat2, _ = geod.fwd(lon, lat, heading, 10)
        adj_h = heading + 30
        
        # 1. Draw Black Border Arrow
        folium.PolyLine([(lat, lon), (lat2, lon2)], color='black', weight=7, opacity=1.0).add_to(group)
        folium.RegularPolygonMarker((lat2, lon2), number_of_sides=3, radius=8, rotation=adj_h, 
                                    color='black', fill_color='black', fill_opacity=1).add_to(group)
        
        # 2. Draw Colored Arrow
        folium.PolyLine([(lat, lon), (lat2, lon2)], color=color, weight=5, opacity=1.0).add_to(group)
        folium.RegularPolygonMarker((lat2, lon2), number_of_sides=3, radius=6, rotation=adj_h, 
                                    color=color, fill_color=color, fill_opacity=1).add_to(group)

    # Drawing function
    def add_to_layer(group, row, lat, lon, heading, val, cmap, tt, html_popup):
        color = cmap(val)
        
        # Draw Arrow FIRST
        if pd.notna(heading):
            draw_arrow(group, lat, lon, heading, color, tt, html_popup)
            
        # Draw Point LAST (So it renders on top of the arrow)
        folium.CircleMarker(
            (lat, lon), radius=8, color='black', 
            fill=True, fill_color=color, fill_opacity=1.0, 
            opacity=1.0, weight=1, tooltip=tt,
            popup=folium.Popup(html_popup, max_width=500)
        ).add_to(group)

    # Main Loop
    for _, row in df.iterrows():
        lat, lon = row.y, row.x
        h = row.heading
        
        # Tooltip text
        tt = f"<b>Score: {row.get('score', 0):.2f}</b><br><u><b>Pos:</b></u><br>"
        tt += "<br>".join([f"{t}: {row.get(t,0):.2f}" for t in positive_tags])
        tt += "<br><u><b>Neg:</b></u><br>"
        tt += "<br>".join([f"{t}: {row.get(t,0):.2f}" for t in negative_tags])
        
        # Popup HTML
        img_path = row.get('path', '')
        html_popup = f"""
        <div style="display: flex; flex-direction: row; align-items: flex-start; width: 400px;">
            <div style="flex: 1; margin-right: 10px; font-size: 12px;">{tt}</div>
            <div style="flex: 1;">
                <a href="{img_path}" target="_blank">
                    <img src="{img_path}" style="width:150px; border:1px solid #ccc; cursor:pointer;">
                </a>
            </div>
        </div>
        """
        
        # Add to layers
        add_to_layer(groups['score'], row, lat, lon, h, row.get('score', 0), pos_cmap, tt, html_popup)
        
        for t in positive_tags:
            if pd.notna(row.get(t)):
                add_to_layer(groups[t], row, lat, lon, h, row[t], pos_cmap, tt, html_popup)
        for t in negative_tags:
            if pd.notna(row.get(t)):
                add_to_layer(groups[t], row, lat, lon, h, row[t], neg_cmap, tt, html_popup)

    folium.LayerControl(collapsed=False).add_to(m)
    return m

In [74]:
m=create_map(gdf,positive_tags,negative_tags)
m.save("map.html")